### ISSUE TITLE
Can you provide Wheel type installation package of slimpy?

### ISSUE THREAD

**Issue by jtyoui** [iosonofabio/slmpy#1]
Hi,I install always fail. 
```
 Using cached slmpy-0.3.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\python3.7\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-m74qp5cb\\slmpy_72136caa5ac443cbb317d7db9e7f1086\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-m74qp5cb\\slmpy_72136caa5ac443cbb317d7db9e7f1086\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dell\AppData\Local\Temp\pip-pip-egg-info-9bqfgarm'
         cwd: C:\Users\dell\AppData\Local\Temp\pip-install-m74qp5cb\slmpy_72136caa5ac443cbb317d7db9e7f1086\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dell\AppData\Local\Temp\pip-install-m74qp5cb\slmpy_72136caa5ac443cbb317d7db9e7f1086\setup.py", line 46, in <module>
        with open('VERSION') as fversion:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

Obviously. it don't find VERSION file from slmpy-0.3.0.tar.gz.
I download source code, manual install `python setup.py sdist`. but fail again!
install error message:
```
(python3.7) PS C:\Users\dell\Desktop\slmpy> python .\setup.py sdist
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\pkgconfig\pkgconfig.py", line 91, in _wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\pkgconfig\pkgconfig.py", line 125, in exists
    return call(cmd) == 0
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\setup.py", line 181, in <module>
    pkgconfig.parse("eigen3")["include_dirs"],
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\pkgconfig\pkgconfig.py", line 248, in parse
    _raise_if_not_exists(package)
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\pkgconfig\pkgconfig.py", line 102, in _raise_if_not_exists
    if not exists(package):
  File "C:\ProgramData\Anaconda3\envs\python3.7\lib\site-packages\pkgconfig\pkgconfig.py", line 93, in _wrapper
    raise EnvironmentError("pkg-config probably not installed: %r" % e)
OSError: pkg-config probably not installed: FileNotFoundError(2, '系统找不到指定的文件。', None, 2, None)
(python3.7) PS C:\Users\dell\Desktop\slmpy>
```

**Comment by iosonofabio** [comment]
Hi @jtyoui 

Thanks for writing. I don't really have time to maintain this anymore, it's also kind of pointless since Leiden was published. Leiden is implemented in igraph now.

Feel free to make a PR if you want this bug fixed.

**Comment by jtyoui** [comment]
@iosonofabio I see. think you for your reply!
