### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by si-naja** [iosonofabio/slmpy#2]
Hello!

I had a problem with installing slmpy.

After installing all the libraries of requirements and trying to install slmpy, the following error occurs: pkgconfig.pkgconfig.PackageNotFoundError: eigen3 not found:

> Full text of error:
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [10 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 36, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\Admin\AppData\Local\Temp\pip-install-qcz2oinq\slmpy_bc7ba80d42744d1aa6a2ae24446400a9\setup.py", line 182, in <module>
>           pkgconfig.parse("eigen3")["include_dirs"],
>         File "C:\Users\Admin\Anaconda3\lib\site-packages\pkgconfig\pkgconfig.py", line 248, in parse
>           _raise_if_not_exists(package)
>         File "C:\Users\Admin\Anaconda3\lib\site-packages\pkgconfig\pkgconfig.py", line 103, in _raise_if_not_exists
>           raise PackageNotFoundError(package)
>       pkgconfig.pkgconfig.PackageNotFoundError: eigen3 not found
>       [end of output]

Installing fresh version of visual studio and older versions of pkgconfig didn't help.

I try it on another computer, and have this error:

> error: metadata-generation-failed
> Encountered error while generating package metadata

Have you experienced this problem?

**Comment by iosonofabio** [comment]
Hi @naja-sirina 

You probably need to install eigen3 in a place where this package can see it. TBH, this package is mostly an exercise for myself since the Leiden algorithm (leidenalg on PyPI) is faster and more stable than this one...

**Comment by si-naja** [comment]
ok. i'll try and write in this post)
